
export const AIRLINES = [

    { code: 'GA', name: 'Garuda Indonesia' },
    { code: 'QG', name: 'Citilink' },
    { code: 'JT', name: 'Lion Air' },
    { code: 'ID', name: 'Batik Air' },
    { code: 'IW', name: 'Wings Air' },
    { code: 'IU', name: 'Super Air Jet' },
    { code: 'QZ', name: 'AirAsia Indonesia' },
    { code: 'SJ', name: 'Sriwijaya Air' },
    { code: 'IN', name: 'NAM Air' },
    { code: 'IP', name: 'Pelita Air' },
    { code: '8B', name: 'TransNusa' },
    { code: 'SI', name: 'Susi Air' },
    { code: 'IL', name: 'Trigana Air' },

    { code: 'SQ', name: 'Singapore Airlines' },
    { code: 'TR', name: 'Scoot' },
    { code: 'MI', name: 'SilkAir' },
    { code: 'MH', name: 'Malaysia Airlines' },
    { code: 'AK', name: 'AirAsia' },
    { code: 'OD', name: 'Batik Air Malaysia' },
    { code: 'VN', name: 'Vietnam Airlines' },
    { code: 'VJ', name: 'VietJet Air' },
    { code: 'BL', name: 'Pacific Airlines' },
    { code: 'TG', name: 'Thai Airways' },
    { code: 'FD', name: 'Thai AirAsia' },
    { code: 'WE', name: 'Thai Smile' },
    { code: 'PR', name: 'Philippine Airlines' },
    { code: '5J', name: 'Cebu Pacific' },
    { code: 'Z2', name: 'Philippines AirAsia' },
    { code: 'BI', name: 'Royal Brunei Airlines' },
    { code: 'MM', name: 'Peach Aviation' },

    { code: 'EK', name: 'Emirates' },
    { code: 'QR', name: 'Qatar Airways' },
    { code: 'EY', name: 'Etihad Airways' },
    { code: 'TK', name: 'Turkish Airlines' },
    { code: 'SV', name: 'Saudia' },
    { code: 'WY', name: 'Oman Air' },
    { code: 'GF', name: 'Gulf Air' },
    { code: 'FZ', name: 'flydubai' },

    { code: 'JL', name: 'Japan Airlines' },
    { code: 'NH', name: 'All Nippon Airways (ANA)' },
    { code: 'KE', name: 'Korean Air' },
    { code: 'OZ', name: 'Asiana Airlines' },
    { code: '7C', name: 'Jeju Air' },
    { code: 'LJ', name: 'Jin Air' },
    { code: 'BX', name: 'Air Busan' },
    { code: 'RS', name: 'Air Seoul' },
    { code: 'CI', name: 'China Airlines' },
    { code: 'BR', name: 'EVA Air' },
    { code: 'CX', name: 'Cathay Pacific' },
    { code: 'CZ', name: 'China Southern Airlines' },
    { code: 'MU', name: 'China Eastern Airlines' },
    { code: 'CA', name: 'Air China' },
    { code: 'MF', name: 'Xiamen Air' },
    { code: 'HU', name: 'Hainan Airlines' },

    { code: 'QF', name: 'Qantas' },
    { code: 'JQ', name: 'Jetstar' },
    { code: 'VA', name: 'Virgin Australia' },
    { code: 'KL', name: 'KLM Royal Dutch Airlines' },
    { code: 'LH', name: 'Lufthansa' },
    { code: 'BA', name: 'British Airways' },
    { code: 'AF', name: 'Air France' },
    { code: 'OTHER', name: 'Other / Lainnya' },
].sort((a, b) => {
    if (a.code === 'OTHER') return 1;
    if (b.code === 'OTHER') return -1;
    return a.name.localeCompare(b.name);
});
